package io.dobby.core.nlu.llm

import io.dobby.core.sock.CommandInvocation
import io.dobby.core.sock.CommandSpec
import io.dobby.core.sock.ParamSpec
import io.dobby.core.sock.ParamType

/**
 * Turns the registry into the two GBNF grammars Tier 2 decodes under.
 *
 * Generated, never written by hand, so a Sock added in M4 is reachable by Tier 2 the moment it
 * is registered — and a Sock *removed* is unreachable in the same breath, which is the half
 * that matters.
 *
 * ### Two grammars, because there are two decisions
 *
 * [route] is a flat alternation of command ids: the model picks a name and stops. [fill] is one
 * command's parameter object: the model has already been told which command it is and only has
 * to say what its values are. Neither has to do the other's job, which is the whole point of
 * the split — see `m6b-plan.md`.
 *
 * ### The decisions that are not obvious
 *
 * - **Rule names use hyphens.** llama.cpp identifies rule names with `is_word_char`, which
 *   accepts `[a-zA-Z0-9-]` and not `_` — verified against the pinned v0.4.1 both ways:
 *   the generated grammar parses, and the same grammar with an underscore fails with
 *   `expecting newline or end`. See `android/llama/tools/gbnf_check.cpp`.
 * - **Route labels are the command ids, verbatim and bare.** Not numbers, not `STOP`. The id is
 *   itself a hint — `clock.whats_the_time` tells a 1.7B model what the line means in a way `7`
 *   cannot, and a numbered list makes it do a positional lookup over eighteen items, which is
 *   exactly what a small model does badly. It also means the gate's lookup does not change and
 *   there is no second vocabulary to keep in sync.
 * - **Every fill grammar has a `"none"` alternative, and it is load-bearing.** In the
 *   single-shot design a required param had no `null`, so a command the model could not fill
 *   was inexpressible and its only exit was `cmd-none`. Once the command has been chosen,
 *   `cmd-none` is gone — and without an escape the model is *forced* to invent
 *   `{"amount":1,…}` for "stell einen timer" said with no duration. `"none"` at fill time means
 *   "the route was right and the sentence still does not contain what this command needs".
 * - **Optional params get a `null` alternative** rather than grammar-level optionality, so the
 *   shape stays fixed and the reply length stays predictable. The decoder drops the nulls and
 *   `ParamCoercion` applies [ParamSpec.default].
 * - **`int` is unrolled to four digits**, not `[0-9]+`: an unbounded repetition invites
 *   `99999999999` and an overflow. Four and not three because "timer 3600 sekunden" is a real
 *   sentence, and three digits would silently turn it into `none`.
 * - **`char ::= [^"\\]`** — text params carry Normalizer output, which has no punctuation left
 *   to escape.
 */
object GrammarGenerator {

    /** Text params are capped here. See [Tier2Json.MAX_STRING] for why the decoder's is larger. */
    const val MAX_TEXT_CHARS: Int = 40

    /** The entry rule of both grammars. */
    const val ROOT: String = "root"

    /**
     * Step 1: pick a command id, or `none`.
     *
     * A flat alternation of literals and nothing else. That shape is also what would make the
     * unique-prefix short-circuit possible later — stop decoding once the emitted prefix can
     * only be one label — but that is a measurement-driven optimisation, not this.
     */
    fun route(catalog: Tier2Catalog): String = buildString {
        appendLine("# Generated by GrammarGenerator.route — do not edit.")
        appendLine("# One literal per command, plus \"${CommandInvocation.NONE}\". The label IS the command id.")
        val labels = catalog.commandIds + CommandInvocation.NONE
        appendLine("$ROOT ::= ${labels.joinToString(" | ") { literal(it) }}")
    }

    /**
     * Step 2: the parameter object for one command, or `none`.
     *
     * Today's per-command branch with the `"c"` head removed, plus the escape. Only ever called
     * for a command in [Tier2Catalog.withParams] — a zero-param command is answered completely
     * by [route], which is what makes the split cheap.
     */
    fun fill(catalog: Tier2Catalog, command: CommandSpec): String {
        require(command.params.isNotEmpty()) {
            "'${command.id}' has no params and needs no fill grammar — route answers it whole"
        }
        return buildString {
            appendLine("# Generated by GrammarGenerator.fill for ${command.id} — do not edit.")
            appendLine("$ROOT ::= ${branch(catalog, command, withCommandKey = false)} | ${literal(CommandInvocation.NONE)}")
            for (param in catalog.paramsOf(command)) {
                val rule = paramRule(param) ?: continue
                appendLine("${catalog.ruleName("p", command.id, param.name)} ::= $rule")
            }
            if (command.params.any { it.type is ParamType.Integer }) {
                appendLine()
                appendLine("# Unrolled rather than [0-9]+: an unbounded repetition invites an overflow.")
                appendLine("int ::= [0-9] | [1-9] [0-9] | [1-9] [0-9] [0-9] | [1-9] [0-9] [0-9] [0-9]")
            }
            if (command.params.any { it.type is ParamType.Text }) {
                appendLine()
                appendLine("string ::= \"\\\"\" char{1,$MAX_TEXT_CHARS} \"\\\"\"")
                appendLine("char ::= [^\"\\\\]")
            }
        }.trimEnd() + "\n"
    }

    /** Every fill grammar, in catalog order. For the golden file and the device contract test. */
    fun fills(catalog: Tier2Catalog): Map<String, String> =
        catalog.withParams.associate { it.id to fill(catalog, it) }

    /**
     * `"{\"amount\":" int ",\"unit\":" p-… "}"`, with or without the `"c"` head.
     *
     * [withCommandKey] is false for a fill grammar, where the command is already decided and
     * re-emitting its id would be ten decode steps spent restating the question.
     */
    private fun branch(catalog: Tier2Catalog, command: CommandSpec, withCommandKey: Boolean): String {
        val params = catalog.paramsOf(command)
        val head = StringBuilder("{")
        if (withCommandKey) head.append("\"${Tier2Json.COMMAND_KEY}\":\"${command.id}\"")
        if (params.isEmpty()) return literal("$head}")

        val parts = mutableListOf<String>()
        for ((index, param) in params.withIndex()) {
            if (index > 0 || withCommandKey) head.append(",")
            head.append("\"").append(param.name).append("\":")
            parts += literal(head.toString())
            parts += valueRule(catalog, command, param)
            head.clear()
            if (index == params.lastIndex) parts += literal("}")
        }
        return parts.joinToString(" ")
    }

    /** The rule reference that produces one param's value. */
    private fun valueRule(catalog: Tier2Catalog, command: CommandSpec, param: ParamSpec): String =
        when {
            paramRule(param) != null -> catalog.ruleName("p", command.id, param.name)
            param.type is ParamType.Integer -> "int"
            else -> "string"
        }

    /**
     * The dedicated rule for a param, or null when a shared `int` / `string` will do.
     *
     * An enumeration always needs one — its values are the whole point — and so does anything
     * optional, because that is where the `null` alternative hangs.
     */
    private fun paramRule(param: ParamSpec): String? {
        val needsRule = param.type is ParamType.Enumeration || !param.required
        if (!needsRule) return null
        val base = when (val type = param.type) {
            is ParamType.Integer -> "int"
            is ParamType.Text -> "string"
            // Declaration order: the Sock author wrote "sekunden, minuten, stunden" in the
            // order somebody would say them, and the model reads the list as written.
            is ParamType.Enumeration -> type.values.joinToString(" | ") { literal("\"$it\"") }
        }
        return if (param.required) base else "$base | \"null\""
    }

    /** Wraps [text] as a GBNF string literal, escaping what the parser needs escaped. */
    private fun literal(text: String): String = buildString {
        append('"')
        for (c in text) {
            when (c) {
                '"' -> append("\\\"")
                '\\' -> append("\\\\")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(c)
            }
        }
        append('"')
    }
}
