package io.dobby.core.nlu.llm

import io.dobby.core.sock.CommandInvocation
import io.dobby.core.sock.CommandSpec
import io.dobby.core.sock.ParamSpec
import io.dobby.core.sock.ParamType

/**
 * Turns the registry into a GBNF grammar: one branch per command, plus `cmd-none`.
 *
 * The grammar is what makes "malformed or unknown-command output is impossible" a property of
 * the system rather than a hope about the model. It is generated, never written by hand, so a
 * Sock added in M4 is reachable by Tier 2 the moment it is registered — and a Sock *removed* is
 * unreachable in the same breath, which is the half that matters.
 *
 * ### The decisions that are not obvious
 *
 * - **Rule names use hyphens.** llama.cpp identifies rule names with `is_word_char`, which
 *   accepts `[a-zA-Z0-9-]` and not `_` — verified against `src/llama-grammar.cpp` at the pinned
 *   v0.4.1. An underscore is a load-time parse error, which is at least loud.
 * - **Optional params get a `null` alternative** rather than grammar-level optionality. The
 *   shape stays fixed — every branch emits every key, always in the same order — which is what
 *   makes the reply length predictable enough for [Tier2.MAX_REPLY_TOKENS] to be derivable. The
 *   decoder drops the nulls and `ParamCoercion` then applies [ParamSpec.default], reusing the
 *   machinery Tier 1 already validates against instead of duplicating it.
 * - **A required param has no `null`**, so a command the model cannot fill is not expressible;
 *   its only way out is `cmd-none`, which is the correct answer in that situation.
 * - **`int` is unrolled to four digits**, not `[0-9]+`. An unbounded repetition invites
 *   `99999999999` and an overflow in the decoder. Four and not three because "timer 3600
 *   sekunden" is a real sentence, and three digits would silently turn it into `none`.
 * - **`char ::= [^"\\]`** — text params carry Normalizer output, which has no punctuation left
 *   to escape.
 */
object GrammarGenerator {

    /** Text params are capped here and in [Tier2Json.MAX_TEXT_CHARS]. */
    const val MAX_TEXT_CHARS: Int = 40

    /** The grammar's entry rule. */
    const val ROOT: String = "root"

    fun generate(catalog: Tier2Catalog): String = buildString {
        val branches = catalog.commands.map { catalog.ruleName("cmd", it.id) } + NONE_RULE
        appendLine("# Generated by GrammarGenerator — do not edit.")
        appendLine("# One branch per command, plus $NONE_RULE. Rule names use hyphens: llama.cpp's")
        appendLine("# is_word_char accepts [a-zA-Z0-9-] and not '_'.")
        appendLine("$ROOT ::= ${branches.joinToString(" | ")}")
        appendLine()
        appendLine("$NONE_RULE ::= ${literal(Tier2Json.encode(CommandInvocation.NONE))}")

        var needsInt = false
        var needsString = false
        for (command in catalog.commands) {
            appendLine()
            appendLine("${catalog.ruleName("cmd", command.id)} ::= ${branch(catalog, command)}")
            for (param in catalog.paramsOf(command)) {
                when (param.type) {
                    is ParamType.Integer -> needsInt = true
                    is ParamType.Text -> needsString = true
                    is ParamType.Enumeration -> Unit
                }
                val rule = paramRule(catalog, command, param) ?: continue
                appendLine("${catalog.ruleName("p", command.id, param.name)} ::= $rule")
            }
        }

        if (needsInt) {
            appendLine()
            appendLine("# Unrolled rather than [0-9]+: an unbounded repetition invites an overflow.")
            appendLine("int ::= [0-9] | [1-9] [0-9] | [1-9] [0-9] [0-9] | [1-9] [0-9] [0-9] [0-9]")
        }
        if (needsString) {
            appendLine()
            appendLine("string ::= \"\\\"\" char{1,$MAX_TEXT_CHARS} \"\\\"\"")
            appendLine("char ::= [^\"\\\\]")
        }
    }.trimEnd() + "\n"

    /** `"{\"c\":\"clock.set_timer\",\"amount\":" int ",\"unit\":" p-… "}"` */
    private fun branch(catalog: Tier2Catalog, command: CommandSpec): String {
        val params = catalog.paramsOf(command)
        if (params.isEmpty()) return literal(Tier2Json.encode(command.id))

        val parts = mutableListOf<String>()
        val head = StringBuilder("{\"${Tier2Json.COMMAND_KEY}\":\"${command.id}\"")
        for ((index, param) in params.withIndex()) {
            head.append(",\"").append(param.name).append("\":")
            parts += literal(head.toString())
            parts += valueRule(catalog, command, param)
            head.clear()
            if (index == params.lastIndex) parts += literal("}")
        }
        return parts.joinToString(" ")
    }

    /** The rule reference that produces one param's value. */
    private fun valueRule(catalog: Tier2Catalog, command: CommandSpec, param: ParamSpec): String =
        when {
            paramRule(catalog, command, param) != null -> catalog.ruleName("p", command.id, param.name)
            param.type is ParamType.Integer -> "int"
            else -> "string"
        }

    /**
     * The dedicated rule for a param, or null when a shared `int` / `string` will do.
     *
     * An enumeration always needs one — its values are the whole point — and so does anything
     * optional, because that is where the `null` alternative hangs.
     */
    private fun paramRule(catalog: Tier2Catalog, command: CommandSpec, param: ParamSpec): String? {
        val base = when (val type = param.type) {
            is ParamType.Integer -> "int"
            is ParamType.Text -> "string"
            // Declaration order: the Sock author wrote "sekunden, minuten, stunden" in the order
            // somebody would say them, and the model reads the list as written.
            is ParamType.Enumeration -> type.values.joinToString(" | ") { literal("\"$it\"") }
        }
        val needsRule = param.type is ParamType.Enumeration || !param.required
        if (!needsRule) return null
        // Optional means "the model may decline to fill it", which the fixed shape expresses as
        // a literal null rather than as an absent key.
        return if (param.required) base else "$base | \"null\""
    }

    /** Wraps [text] as a GBNF string literal, escaping what the parser needs escaped. */
    private fun literal(text: String): String = buildString {
        append('"')
        for (c in text) {
            when (c) {
                '"' -> append("\\\"")
                '\\' -> append("\\\\")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(c)
            }
        }
        append('"')
    }

    /** The branch for "no command fits", and the only meaning of [CommandInvocation.NONE]. */
    const val NONE_RULE: String = "cmd-none"
}
